apiVersion: apps/v1
kind: Deployment
metadata:
  name: qiskit-dev-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: qiskit-dev-operator
  template:
    metadata:
      labels:
        name: qiskit-dev-operator
    spec:
      serviceAccountName: qiskit-dev-operator
      containers:
        - name: qiskit-dev-operator
          # Replace this with the built image name
          image: singhp11/qiskit-dev-operator:demo
          command:
          - qiskit-dev-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "qiskit-dev-operator"
